### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by BarbzYHOOL** [Indemos/Terminal#1]
Hello,

I'm looking for a trading (manual) backtester platform (for forex mostly), that works on Linux, and stumbled upon this

is it that kind of thing?

If so, any release?

**Comment by artemiusgreat** [comment]
This repo doesn't have dependencies on Windows, so yes, should run fine on Linux, although I haven't touched Linux for a while. 
When I finish with tests, this could be considered as release of some sort. 
Maybe by the end of the week, but no promises.

**Comment by BarbzYHOOL** [comment]
ok but to make sure, i'm in search of a manual backtesting tool, not automated bots, being able to draw on charts and stuff (i'm not a crazy programmer but before programming a strategy, i need to be able to trade manually, obviously :P)

**Comment by artemiusgreat** [comment]
No, I'm not planning to add the ability to draw on charts, everything is purely algorithmic, including trading and all indicators. 
The only thing that can simplify manual trading that I added is the control over the speed of backtesting and the ability to stop and resume. If you need something more sophisticated, you would have way better chances with public platforms created specifically for manual trading, e.g. ThinkOrSwim or MetaTrader. 

If you're going the route of implementing something on your own, you might try to use this terminal, but replace the chart with the one that allows drawing on it, e.g. this one. 

https://techanjs.org

**Comment by BarbzYHOOL** [comment]
thx
